### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by fresheneesz** [khamidou/kite#16]
No commits for 2 years, demo doesn't work. The readme still implies that its not in a usable state. Yet there are over 1000 stars. Is this project usable?

**Comment by mbijon** [comment]
Kite has said its obsolete for a while on the landing page:
"(Obsolete, use https://github.com/inboxapp/inbox instead)"

Agreed on the star system issues. Now that Github is older and projects are aging it does need some rating method other than stars, or at least to expose stars per-year...

**Comment by fresheneesz** [comment]
Oh I see, it says it up at the top. I never read that. I'm gonna add that obsolete note to the readme.

**Comment by fresheneesz** [comment]
https://github.com/khamidou/kite/pull/17

**Comment by fresheneesz** [comment]
@mbijon Actually, it looks like even the obsolescence note is obsolete. inboxapp seems to not exist anymore. It links to something called nylas, which isn't a webmail application.
