### ISSUE TITLE
BIG issue with demo link http://kiteapp.io/app

### ISSUE THREAD

**Issue by evil4u** [khamidou/kite#18]
The domain name is redirect to http://kiteapp.io/app

This is a big issue people.

<img width="720" alt="screenshot 2019-02-07 at 09 44 12" src="https://user-images.githubusercontent.com/46950707/52402736-f5594f80-2abc-11e9-9612-7c8bd6f779d5.png">

**Comment by Mechazawa** [comment]
The webpage tries to install a malicious plugin under the guise of security

**Comment by khamidou** [comment]
@evil4u @Mechazawa thanks for taking the time to filling an issue on an old project! I've removed any references to this domain name from the readme and the Github description.
